/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CoreAppHeader: typeof import('./src/components/core/app/header/CoreAppHeader.vue')['default']
    CoreBtn: typeof import('./src/components/core/CoreBtn.vue')['default']
    CoreContactForm: typeof import('./src/components/core/CoreContactForm.vue')['default']
    CoreDivider: typeof import('./src/components/core/CoreDivider.vue')['default']
    CoreFooter: typeof import('./src/components/core/app/CoreFooter.vue')['default']
    CoreInput: typeof import('./src/components/core/inputs/CoreInput.vue')['default']
    CoreMdWrapper: typeof import('./src/components/core/containers/CoreMdWrapper.vue')['default']
    CoreMenu: typeof import('./src/components/core/containers/CoreMenu.vue')['default']
    CoreNavButtons: typeof import('./src/components/core/app/header/CoreNavButtons.vue')['default']
    CoreNavDrawer: typeof import('./src/components/core/containers/CoreNavDrawer.vue')['default']
    CoreNavMenu: typeof import('./src/components/core/app/header/CoreNavMenu.vue')['default']
    CoreOverlay: typeof import('./src/components/core/containers/CoreOverlay.vue')['default']
    CorePostList: typeof import('./src/components/core/posts/CorePostList.vue')['default']
    CorePostListItem: typeof import('./src/components/core/posts/CorePostListItem.vue')['default']
    CoreSheet: typeof import('./src/components/core/CoreSheet.vue')['default']
    CoreTextarea: typeof import('./src/components/core/inputs/CoreTextarea.vue')['default']
    CoreToast: typeof import('./src/components/core/feedback/CoreToast.vue')['default']
    PostsRecent: typeof import('./src/components/posts/PostsRecent.vue')['default']
    ProjectListItem: typeof import('./src/components/projects/ProjectListItem.vue')['default']
    ProjectsList: typeof import('./src/components/projects/ProjectsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
