/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CoreAppHeader: typeof import('./src/core/components/app/header/CoreAppHeader.vue')['default']
    CoreBtn: typeof import('./src/core/components/CoreBtn.vue')['default']
    CoreContactForm: typeof import('./src/core/components/CoreContactForm.vue')['default']
    CoreDivider: typeof import('./src/core/components/CoreDivider.vue')['default']
    CoreFooter: typeof import('./src/core/components/app/CoreFooter.vue')['default']
    CoreInput: typeof import('./src/core/components/inputs/CoreInput.vue')['default']
    CoreMdWrapper: typeof import('./src/core/components/containers/CoreMdWrapper.vue')['default']
    CoreMenu: typeof import('./src/core/components/containers/CoreMenu.vue')['default']
    CoreNavButtons: typeof import('./src/core/components/app/header/CoreNavButtons.vue')['default']
    CoreNavMenu: typeof import('./src/core/components/app/header/CoreNavMenu.vue')['default']
    CorePostList: typeof import('./src/core/components/posts/CorePostList.vue')['default']
    CorePostListItem: typeof import('./src/core/components/posts/CorePostListItem.vue')['default']
    CoreTextarea: typeof import('./src/core/components/inputs/CoreTextarea.vue')['default']
    CoreToast: typeof import('./src/core/components/feedback/CoreToast.vue')['default']
    KnowledgeNavListItem: typeof import('./src/pages/knowledge/components/KnowledgeNavListItem.vue')['default']
    KnowledgeNavMenu: typeof import('./src/pages/knowledge/components/KnowledgeNavMenu.vue')['default']
    ProjectListItem: typeof import('./src/pages/projects/components/ProjectListItem.vue')['default']
    ProjectsList: typeof import('./src/pages/projects/components/ProjectsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
